### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by zzterrozz** [btastic/flutter_native_image#78]

**Comment by Hwan-seok** [comment]
👍🏻👍🏻
If you do not mind, could you tell me when is the milestone?

**Comment by zzterrozz** [comment]
@dw2kim  did the job already and pushed a PR that has not been accepted yet. 

You can use tu with that way in your pubspec.yaml: 


flutter_native_image:
    git:
      url: git://github.com/dw2kim/flutter_native_image.git

**Comment by Hwan-seok** [comment]
should write branch name also.
Use
```
  flutter_native_image:
    git:
      url: git://github.com/dw2kim/flutter_native_image
      ref: feature/null-safety-support
```
instead
```
  flutter_native_image:
      git:
        url: git://github.com/dw2kim/flutter_native_image.git
```
